# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: "Grupo de Neuroimagem"
email:
facebook_username: "Neuroimagem-da-Cognição-Humana-134547950058577"
twitter_username:
github_username: "neuroimagem-pucrs"
address: "Av. Ipiranga, 6690 - Jardim Botânico"
  - line: "Porto Alegre - RS, 91410-000"
  - line:
  # Feel free to add more lines here 
telephone: "(51) 3320-5959"
copyright:

# API settings
google_api_key: "AIzaSyDRAblBOS0djWXbUvVPEo6UXVgu-BQ5TCQ"

# Build settings
markdown: kramdown
