# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Laboratório de Imagens -LABIMA
email:
facebook_username: Neuroimagem-da-Cognição-Humana-134547950058577
twitter_username:
github_username: neuroimagem-pucrs
address:
   - line: Avenida Ipiranga, 6681
   - line: Prédio 30 - Sala 218
   - line: Porto Alegre - RS - Brasil
   - line: CEP: 90619-900
  # Feel free to add more lines here 
telephone: (51) 3320-5959
copyright:

# API settings
google_api_key: AIzaSyAtGoV75QWUSEbfqxl-5bR2A-Tw86D6xqo

# Build settings
markdown: kramdown
